name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: "ec2-13-201-188-227.ap-south-1.compute.amazonaws.com"
        EC2_USER: "root"
      run: |
        # Save the private key to a file
        echo "$EC2_SSH_KEY" > blasbloom.pem
        chmod 600 blasbloom.pem

        # Add host key to known_hosts
        ssh-keyscan -H $EC2_HOST >> ~/root/.ssh/known_hosts

        # Connect to EC2 and deploy
        ssh -T -i blasbloom.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /root/github/nodeapp
          git pull origin main
          npm install
          pm2 stop all || true
          pm2 start server.js --name nodeapp
        EOF

        # Cleanup
        rm -f blasbloom.pem

