name: Deploy to EC2

on:
  push:
    branches:
      - main  # This triggers the workflow on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up SSH and deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # GitHub secret for private key
        EC2_HOST: ec2-13-201-188-227.ap-south-1.compute.amazonaws.com  # Your EC2 instance address
        EC2_USER: ubuntu  # Use ubuntu user for SSH (not root)
      run: |
        # Install OpenSSH Client (ensure it's available)
        sudo apt-get install -y openssh-client

        # Create the .ssh directory and set permissions
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Save the private key to a file and set permissions
        echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the EC2 host to known_hosts to prevent SSH warning
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # Use ssh-agent to load the private key
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa

        # SSH into EC2 and deploy as ubuntu user, then switch to root
        ssh -o StrictHostKeyChecking=no -T $EC2_USER@$EC2_HOST << 'EOF'
          # Switch to root user
          sudo su -

          # Install pm2 globally if not installed
          npm install -g pm2

          # Navigate to the app directory (create if not exists)
          cd /root/github/nodeapp || mkdir -p /root/github/nodeapp
          cd /root/github/nodeapp

          # Pull the latest code from GitHub
          git pull origin main

          # Install dependencies (if any)
          npm install

          # Restart the Node.js app with pm2
          pm2 stop all || true
          pm2 start server.js --name nodeapp
        EOF

